CREATE DATABASE LAVAZEMKHONEGI;

DROP SCHEMA IF EXISTS `LAVAZEMKHONEGI`;

CREATE SCHEMA IF NOT EXISTS `LAVAZEMKHONEGI` DEFAULT CHARACTER SET latin1;

USE `LAVAZEMKHONEGI`;

CREATE TABLE IF NOT EXISTS `LAVAZEMKHONEGI`.`PRODUCTS` (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    BRAND VARCHAR(255) NOT NULL,
    QUANTITY_IN_STOCK INT NOT NULL,
    PRICE INT NOT NULL,
    ATTRIBUTES json NOT NULL
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `LAVAZEMKHONEGI`.`CUSTOMERS` (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    MOBILE_NUMBER INT NOT NULL,
    EMAIL VARCHAR(255) UNIQUE,
    pass VARCHAR(255) NOT NULL,
    MELI_CODE INT UNIQUE,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    UNIQUE (MOBILE_NUMBER)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `LAVAZEMKHONEGI`.`SHIPPERS` (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `LAVAZEMKHONEGI`.`RATE` (
    NUMBER INT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRIMARY KEY (CUSTOMER_ID, PRODUCT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `LAVAZEMKHONEGI`.`WISHLIST` (
    CUSTOMER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRIMARY KEY (CUSTOMER_ID, PRODUCT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `LAVAZEMKHONEGI`.`COMMENT` (
    CONTENT LONGTEXT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    PRIMARY KEY (PRODUCT_ID, CUSTOMER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `LAVAZEMKHONEGI`.`CART` (
    QUANTITY INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    PRIMARY KEY (PRODUCT_ID, CUSTOMER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `LAVAZEMKHONEGI`.`CUSTOMER_ADDRESSES` (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    STATE VARCHAR(255) NOT NULL,
    CITY VARCHAR(255) NOT NULL,
    DETAIL LONGTEXT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `LAVAZEMKHONEGI`.`ORDERS` (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SHIPP_DATE DATE NOT NULL,
    ORDER_DATE DATE NOT NULL,
    SHIPP_PRICE INT NOT NULL,
    SHIPP_CODE INT NOT NULL,
    RECIEVER_NAME VARCHAR(255) NOT NULL,
    RECIEVER_PHONE INT NOT NULL,
    SHIPPER_ID INT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    FOREIGN KEY (SHIPPER_ID) REFERENCES SHIPPERS(ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `LAVAZEMKHONEGI`.`ORDER_DETAILS` (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    QUANTITY INT NOT NULL,
    PURCHASE_PRICE INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    ORDER_ID INT NOT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `LAVAZEMKHONEGI`.`CATEGORY` (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PARENT_ID INT NOT NULL,
    FOREIGN KEY (PARENT_ID) REFERENCES CATEGORY(ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `LAVAZEMKHONEGI`.`BEING_IN_CATEGORY` (
    PRODUCT_ID INT NOT NULL,
    CATEGORY_ID INT NOT NULL,
    PRIMARY KEY (PRODUCT_ID, CATEGORY_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;